Service AddInfrastructure, Task AuthenticateByPasswordAsync
Krammatik/frontend pull request #1
Opened 2022-05-16 11:20 UTC by samialassafinggm

Token Response ✔

2022-05-17 07:16 UTC, DeathsGun requested changes

2022-05-17 07:16 UTC, DeathsGun commented on Infrastructure_Layer/Services/SwaggerClient.cs
> +    public class SwaggerClient : ISwaggerClient
Wäre KrammatikService als name nicht besser? Hat ja eigentlich nichts mit Swagger zu tun

2022-05-17 07:16 UTC, DeathsGun commented on Application_Layer/Common/Interfaces/ISwaggerClient.cs
> +    public interface ISwaggerClient
Wie auch im in der Impl würde ich es eher IKrammatikService nennen

2022-05-17 08:11 UTC, samialassafinggm commented on Infrastructure_Layer/Services/SwaggerClient.cs
> +    public class SwaggerClient : ISwaggerClient
ja hast du recht, habe eben geändert

2022-05-17 08:30 UTC, samialassafinggm commented on Infrastructure_Layer/Common/Models/Swagger/Response/Authentication/AuthentictionResponseModel.cs
> +        // should i convert it to Base 64 then save it ?
das geht mir nicht darum, um zu wissen, wie ich mein Token Response zu speichen, und wider für den Anderen Request mit senden zu können. sonst ist mein Response unauthorisd weißt du ?

2022-05-17 09:15 UTC, DeathsGun commented on Infrastructure_Layer/Common/Models/Swagger/Response/Authentication/AuthentictionResponseModel.cs
> +        // should i convert it to Base 64 then save it ?
Ja deswegen entweder Cookies oder im Sitzungszustand https://docs.microsoft.com/de-de/aspnet/core/fundamentals/app-state?view=aspnetcore-6.0

2022-05-20 15:53 UTC, DeathsGun approved these changes
Jetzt sieht es gut aus

2022-05-20 15:53 UTC, merged